### PR TITLE
Python3 support.

### PR DESCRIPTION
**Pull request by sebftw**
I managed to get the script to run on python 3.

First I ran it through 2to3, and then i modified it manually near line 34 (thanks to this [issue comment](https://github.com/vadimkantorov/caffemodel2pytorch/issues/4#issuecomment-462759910))
And finally, line 387 (in the new file), where i added an 'rb' to the open command.

I have not tested it extensively, but it worked fine for converting a caffemodel to pth format in my case.
To make it work i ran "pip install protobuf" and I also downloaded [protoc-3.7.0-win64.zip](https://github.com/protocolbuffers/protobuf/releases) and simply put the binary in my PATH.

Hope it can help out some other users, especially since pytorch is not supported for python 2 on Windows.

### CODE REVIEW

**Comment by vadimkantorov** [comment]
If changes are small, do you mind sending a PR against the main `caffemodel2pytorch.py` file to make it work on python3 (instead of adding a separate `caffemodel2pytorch_python3.py` file)? Thank you!

**Comment by sebftw** [comment]
I can do that, but it may not be compatible with python2 anymore then. (2to3 made many changes) And I haven't tested any functionality other than converting a .caffemodel to .caffemodel.pth.

Maybe you can see if it is backwards compatible with python2? I can't run it, since I don't have pytorch in python2. It would also be a good idea to completely test the IO first, at least, since that was the most troubling aspect when porting.

**Comment by vadimkantorov** [comment]
Please do that, and we'll see the 2to3 diff in the GitHub ui

**Comment by sebftw** [comment]
Continued in https://github.com/vadimkantorov/caffemodel2pytorch/pull/7.

**Pull request closed without merging**
